version: "3"

services:

  my-sql-server:
    image: mysql:8.0.1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass
    networks:
      - my-network
    volumes:
      - ./my-data:/var/lib/mysql

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8000:80
    environment:
      PMA_HOST: my-sql-server
      # PMA_USER: root
      # PMA_PASSWORD: mypass
      PMA_ABSOLUTE_URI: https://phpmyadmin.votechain.in
    networks:
      - my-network
    depends_on:
      - my-sql-server

  ganache-rpc:
    image: trufflesuite/ganache-cli:v6.8.1
    ports:
      - 8545:8545
    volumes:
      - ./chain-data:/ganache_data
    command: ["--db=/ganache_data", "--mnemonic='kiwi visit marble accident acid urge lumber type picnic have split charge'"]
    networks:
      - my-network

networks:
  my-network:
